# Generated by Django 4.1.2 on 2022-10-18 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_remove_playlist_songs_songplaylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="genre",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="recording_artists", to="music.genre"),
            preserve_default=False,
        ),
    ]
