# Generated by Django 4.1.2 on 2022-10-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_remove_playlist_songs_songplaylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="songs", to="music.genre"),
        ),
    ]
