# Generated by Django 4.1.2 on 2022-10-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_song_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(related_name="playlists", to="music.song"),
        ),
    ]
